# Generated by Django 5.0.3 on 2024-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_book_author_delete_author_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_code', models.CharField(default='+254', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.FileField(upload_to='')),
                ('user_type', models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], default='employee', max_length=20)),
            ],
        ),
    ]
