# Generated by Django 5.0.3 on 2024-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datbase1', models.FloatField()),
                ('datbase2', models.FloatField()),
            ],
        ),
    ]
