# Generated by Django 5.0.3 on 2024-04-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='datbase1',
            new_name='database1',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='datbase2',
            new_name='database2',
        ),
    ]
